apiVersion: v1
kind: Service
metadata:
  name: store-fe
  labels:
    name: store-fe
spec:
  sessionAffinity: ClientIP
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 80
  type: NodePort
  selector:
    name: store-fe
